name: mt.Vicuna Simple Theme Set
id: mtVicunaSimple
#key: MT::Plugin::mtVicunaSimple
description: <__trans phrase="Plugin for a MT5 Simple Theme for Vicuna CMS.">
author_name: <__trans phrase="oscar">
author_link: http://www.zelazny.mydns.jp/
plugin_link: http://code.zelazny.mydns.jp/trac/theme/wiki/mtVicuna/Simple
doc_link: http://mt.vicuna.jp/
l10n_lexicon:
  ja: l10n_ja.yaml
version: 1.02

themes:
  mtVicunaSimple:
    id: mtVicunaSimple
    label: mt.Vicuna Simple Theme
    description: <__trans phrase="A MT5 Theme for Vicuna CMS.">
    author_name: wu
    author_link: http://3ping.org/
    version: 2.3.2
    class: blog
    static_path: blog_static
    l10n_lexicon:
      ja: l10n_ja.yaml
    thumbnail_file: vicuna.png
    thumbnail_file_medium: vicuna-medium.png
    thumbnail_file_small: vicuna-small.png
    elements:
      blog_static_files: 
        component: core
        importer: blog_static_files
        require: 1
        data: 
          - themes
      default_prefs:
        component: core
        importer: default_prefs
        require: 1
        data:
          file_extension: html
          convert_paras: __default__
          convert_paras_comments: __default__
          archive_type_preferred: Individual
          entries_on_index: 10
      template_set:
        component: core
        importer: template_set
        name: Template Set
        data:
          label: mt.Vicuna Simple
          base_path: templates
          require: 1
          base_css: 0
          stylecatcher_libraries:
            mtvicuna_skin:
              url: '{{support}}theme_static/mtVicunaSimple/'
              label: mt.Vicuna skin
              description_label: 'Styles that are compatible with the mt.Vicuna Theme.'
#            mtvicuna_recent_skin:
#              url: 'http://code.zelazny.mydns.jp/themes/mtVicuna-recent/'
#              label: mt.Vicuna Recent skin
#              description_label: 'Recent Vicuna Styles of the mt.Vicuna Theme.'
            mtvicuna_legacy_skin:
              url: 'http://code.zelazny.mydns.jp/themes/mtVicuna-legacy/'
              label: mt.Vicuna Legacy skin
              description_label: 'Legacy Vicuna Styles covert to Recent version of the mt.Vicuna Theme.'
            hashim_skin:
              url: 'http://kita2.net/stylelib/'
              label: mt.Vicuna HashiM Stylelib
              description_label: 'This is style library only for the mtVicuna theme.'
          templates:
            index:
              main_index:
                label: Main Index
                outfile: index.html
                rebuild_me: 1
              archive_index:
                label: Archive Index
                outfile: archives/index.html
                rebuild_me: 1
              styles:
                label: Stylesheet
                outfile: styles.css
                rebuild_me: 1
              feed_recent:
                label: Feed - Recent Entries
                outfile: atom.xml
                rebuild_me: 1
              rsd:
                label: RSD
                outfile: rsd.xml
                rebuild_me: 1
              javascript:
                label: JavaScript
                outfile: js/mt.js
                rebuild_me: 1
              user_jquery:
                label: User JQuery
                outfile: js/user_jquery.js
                rebuild_me: 1
              google_sitemap:
                label: SiteMap 0.9
                outfile: sitemap.xml
                rebuild_me: 1
              wxr_rss2: 
                label: ExtendedRSS 2.0
                outfile: rss.xml
                rebuild_me: 1
            individual:
              entry:
                label: Entry
                filename: archiveTemplate/entry.mtml
                mappings:
                  entry_archive:
                    archive_type: Individual
                    file_template: %y/%m/%-f
            archive:
              category_entry_listing:
                label: Category Entry Listing
                filename: archiveTemplate/category_entry_listing.mtml
                mappings:
                  category:
                    archive_type: Category
                    file_template: %-c/%i
                  category-monthly: 
                    archive_type: Category-Monthly
                    file_template: "%-c/%y/%m/%i"
              monthly_entry_listing:
                label: Monthly Entry Listing
                filename: archiveTemplate/monthly_entry_listing.mtml
                mappings:
                  monthly:
                    archive_type: Monthly
                    file_template: %y/%m/%i
            page:
              page:
                label: Page
                filename: archiveTemplate/page.mtml
                mappings:
                  page_archive:
                    archive_type: Page
                    file_template: %-c/%-f
            module:
              banner_header:
                label: Banner Header
                filename: templateModule/banner_header.mtml
              banner_footer:
                label: Banner Footer
                filename: templateModule/banner_footer.mtml
              html_head:
                label: HTML Head
                filename: templateModule/html_head.mtml
              topic_path:
                label: Topic Path
                filename: templateModule/topic_path.mtml
              sidebar:
                label: Sidebar
                filename: templateModule/sidebar.mtml
              entry_summary:
                label: Entry Summary
                filename: templateModule/entry_summary.mtml
              related_entries:
                label: Related Entries
                filename: templateModule/related_entries.mtml
              comments:
                label: Comments
                filename: templateModule/comments.mtml
              comment_detail:
                label: Comment Detail
                filename: templateModule/comment_detail.mtml
              trackbacks:
                label: TrackBacks
                filename: templateModule/trackbacks.mtml
              next_entry_link_simple:
                label: Next Entry Link Simple
                filename: templateModule/next_entry_link_simple.mtml
              next_entry_link_detailed:
                label: Next Entry Link Detailed
                filename: templateModule/next_entry_link_detailed.mtml
              headline:
                label: Headline
                filename: templateModule/headline.mtml
              global_navigation:
                label: Global Navigation
                filename: templateModule/global_navigation.mtml
              hatebu_anywhere:
                label: Hatena Bookmark Anywhere
                filename: templateModule/hatebu_anywhere.mtml
            system:
              comment_preview:
                label: Comment Preview
                description_label: Displays preview of comment.
                filename: system/comment_preview.mtml
              comment_response:
                label: Comment Response
                description_label: 'Displays error, pending or confirmation message for comments.'
                filename: system/comment_response.mtml
              comment_listing:
                description_label: Improved listing of comments.
                label: Comment Listing
                filename: system/comment_listing.mtml
              dynamic_error:
                label: Dynamic Error
                description_label: Displays errors for dynamically published templates.
                filename: system/dynamic_error.mtml
              popup_image:
                label: Popup Image
                description_label: Displays image when user clicks a popup-linked image.
                filename: system/popup_image.mtml
              search_results:
                label: Search Results
                description_label: Displays results of a search.
                filename: system/search_results.mtml
            widgetset:
              primary_sidebar:
                order: 1000
                label: Primary Sidebar
                widgets:
                  - Calender
                  - Search
                  - Recent Entries
                  - Recent Comments
                  - Recent Trackbacks
                  - Recent Assets
                  - Tag Cloud
                  - About This Page
              secondary_sidebar:
                order: 1000
                label: Secondary Sidebar
                widgets:
                  - Category Archives
                  - Monthly Archives
                  - Page Listing
                  - Syndication
                  - OpenID Accepted
                  - Powered By
            widget:
              about_this_page:
                label: About This Page
                filename: widget/about_this_page.mtml
              archives_list:
                label: Archives
                filename: widget/archives_list.mtml
              monthly_archives_dropdown:
                label: Monthly Archives Dropdown
                filename: widget/monthly_archives_dropdown.mtml
              category_archive_list:
                label: Category Archives
                filename: widget/category_archive_list.mtml
              calendar:
                label: Calender
                filename: widget/calendar.mtml
              recent_comments:
                label: Recent Comments
                filename: widget/recent_comments.mtml
              recent_trackbacks:
                label: Recent Trackbacks
                filename: widget/recent_trackbacks.mtml
              recent_entries:
                label: Recent Entries
                filename: widget/recent_entries.mtml
              recent_assets:
                label: Recent Assets
                filename: widget/recent_assets.mtml
              recent_entry_assets:
                label: Recent Entry Assets
                filename: widget/recent_entry_assets.mtml
              syndication:
                label: Syndication
                filename: widget/syndication.mtml
              links:
                label: Links
                filename: widget/links.mtml
              search:
                label: Search
                filename: widget/search.mtml
              tag_cloud:
                label: Tag Cloud
                filename: widget/tag_cloud.mtml
              creative_commons:
                label: Creative Commons
                filename: widget/creative_commons.mtml
              openid:
                label: OpenID Accepted
                filename: widget/openid.mtml
              signin:
                label: Sign in
                filename: widget/signin.mtml
              author_archive_list:
                label: Author Archives
                filename: widget/author_archive_list.mtml
              current_author_monthly_archive_list:
                label: Current Author Monthly Archives
                filename: widget/current_author_monthly_archive_list.mtml
              current_category_monthly_archive_list:
                label: Current Category Monthly Archives
                filename: widget/current_category_monthly_archive_list.mtml
              date_based_author_archives:
                label: Date-Based Author Archives
                filename: widget/date_based_author_archives.mtml
              date_based_category_archives:
                label: Date-Based Category Archives
                filename: widget/date_based_category_archives.mtml
              pages_list:
                label: Page Listing
                filename: widget/pages_list.mtml
              powered_by:
                label: Powered By
                filename: widget/powered_by.mtml
              blogs:
                label: Blog Listing
                filename: widget/blogs.mtml
              monthly_archives_list:
                label: Monthly Archives
                filename: widget/monthly_archives_list.mtml

blog_config_template: tmpl/blog_config.tmpl
settings:
  index_style:
    default: default
    scope: blog
  entry_style:
    default: default
    scope: blog
  monthly_style:
    default: default
    scope: blog
  category_style:
    default: default
    scope: blog
  eyecatch_style:
    default: eye-h
    scope: blog
  navi_on_top:
    default: 0
    scope: blog
  left_align:
    default: 0
    scope: blog
  fixed_width:
    default: none
    scope: blog
  cloud_style:
    default: none
    scope: blog
  use_slimbox:
    default: 1
    scope: blog
tags:
  function:
    VicunaIndexStyle:    $mtVicunaSimple::mtVicunaSimple::Plugin::tag_index_style
    VicunaEntryStyle:    $mtVicunaSimple::mtVicunaSimple::Plugin::tag_entry_style
    VicunaMonthlyStyle:  $mtVicunaSimple::mtVicunaSimple::Plugin::tag_monthly_style
    VicunaCategoryStyle: $mtVicunaSimple::mtVicunaSimple::Plugin::tag_category_style
    VicunaEyecatch:      $mtVicunaSimple::mtVicunaSimple::Plugin::tag_eyecatch
    VicunaFixedWidth:    $mtVicunaSimple::mtVicunaSimple::Plugin::tag_fixed_width
    VicunaTagcloudStyle: $mtVicunaSimple::mtVicunaSimple::Plugin::tag_cloud_style
  block:
    IfVicunaNavionTop?:  $mtVicunaSimple::mtVicunaSimple::Plugin::if_nav_on_top
    IfVicunaLeftAlign?:  $mtVicunaSimple::mtVicunaSimple::Plugin::if_left_align
    IfVicunaUseSlimbox?: $mtVicunaSimple::mtVicunaSimple::Plugin::if_use_slimbox
callbacks:
    template_param.asset_options_image: $mtVicunaSimple::mtVicunaSimple::Plugin::_asset_options_image
    template_param.asset_insert:        $mtVicunaSimple::mtVicunaSimple::Plugin::_asset_insert_param
    blog_template_set_change: >>
        sub {
            my ($cb, $param) = @_;
            my $blog = $param->{blog};
            my $blog_template_set = $blog->template_set || '';
            return 1
                if 'mtVicunaSimple' ne $blog_template_set;
            $blog->page_layout('double');
            $blog->save;
        }
applications:
    cms:
        menus:
            design:edit_themeparams:
                label: Edit Vicuna Layout
                order: 300
                mode: edit_themeparams
                view:
                    - blog
                    - website
                condition: $mtVicunaSimple::mtVicunaSimple::Plugin::_if_vicuna
        methods:
            edit_themeparams: $mtVicunaSimple::mtVicunaSimple::Plugin::_edit_themeparams
